
unused = "#79e11a"

[nord]
  gray1 = "#464752"
  gray2 = "#565761"
  gray3 = "#b6b6b2"
  gray4 = "#ccccc7"
  black = "#282a36"
  blue = "#6272a4"
  cyan = "#8be9fd"
  green = "#50fa7b"
  magenta = "#ff79c6"
  orange = "#ffb86c"
  purple = "#bd93f9"
  red = "#00ff00"
  white = "#f8f8f2"
  yellow = "#f1fa8c"

[dark]
  button = ["nord.black","nord.gray3"]
  button-focus = ["nord.black","nord.magenta"]
  button-selected = ["nord.white","nord.gray3"]
  cmdline = ["nord.black","nord.yellow"]
  cmdline-button = ["nord.yellow","nord.black"]
  cmdline-border = ["nord.black","nord.yellow"]
  copy-mode = ["nord.black","nord.yellow"]
  copy-mode-alt = ["nord.yellow","nord.black"]
  copy-mode-label = ["nord.white","nord.red"]
  current-capture = ["nord.white","themes.unused"]
  dialog = ["nord.black","nord.yellow"]
  dialog-button = ["nord.yellow","nord.black"]
  default = ["nord.white","nord.black"]
  filter-empty = ["nord.black","nord.cyan"]
  filter-intermediate = ["nord.black","nord.orange"]
  filter-invalid = ["nord.black","nord.red"]
  filter-menu = ["nord.white","nord.black"]
  filter-valid = ["nord.black","nord.green"]
  hex-byte-selected = ["nord.white","nord.purple"]
  hex-byte-unselected = ["nord.white","nord.black"]
  hex-field-selected = ["nord.black","nord.cyan"]
  hex-field-unselected = ["nord.black","nord.white"]
  hex-interval-selected = ["nord.white","nord.gray2"]
  hex-interval-unselected = ["nord.white","nord.gray1"]
  hex-layer-selected = ["nord.white","nord.gray2"]
  hex-layer-unselected = ["nord.white","nord.gray1"]
  packet-list-cell-focus = ["nord.white","nord.purple"]
  packet-list-cell-selected = ["nord.white","nord.gray2"]
  packet-list-row-focus = ["nord.white","nord.cyan"]
  packet-list-row-selected = ["nord.white","nord.gray1"]
  packet-struct-focus = ["nord.black","nord.cyan"]
  packet-struct-selected = ["nord.black","nord.gray2"]
  progress-complete = ["nord.white","nord.purple"]
  progress-default = ["nord.white","nord.black"]
  progress-spinner = ["nord.yellow","nord.purple"]
  spinner = ["nord.yellow","nord.black"]
  stream-client = ["nord.black","nord.red"]
  stream-match = ["nord.black","nord.yellow"]
  stream-search = ["nord.black","nord.white"]
  stream-server = ["nord.white","nord.blue"]
  title = ["nord.red","unused"]

[light]
  button = ["nord.black","nord.white"]
  button-focus = ["nord.black","nord.purple"]
  button-selected = ["nord.black","nord.gray3"]
  cmdline = ["nord.black","nord.yellow"]
  cmdline-button = ["nord.yellow","nord.black"]
  cmdline-border = ["nord.black","nord.yellow"]
  copy-mode = ["nord.white","nord.yellow"]
  copy-mode-alt = ["nord.yellow","nord.white"]
  copy-mode-label = ["nord.black","nord.red"]
  current-capture = ["nord.black","unused"]
  dialog = ["nord.black","nord.yellow"]
  dialog-button = ["nord.yellow","nord.black"]
  default = ["nord.black","nord.white"]
  filter-empty = ["nord.black","nord.cyan"]
  filter-intermediate = ["nord.black","nord.orange"]
  filter-invalid = ["nord.black","nord.red"]
  filter-menu = ["nord.black","nord.white"]
  filter-valid = ["nord.black","nord.green"]
  hex-byte-selected = ["nord.white","nord.purple"]
  hex-byte-unselected = ["nord.black","nord.white"]
  hex-field-selected = ["nord.black","nord.cyan"]
  hex-field-unselected = ["nord.black","nord.gray2"]
  hex-interval-selected = ["nord.white","nord.gray2"]
  hex-interval-unselected = ["nord.black","nord.gray4"]
  hex-layer-selected = ["nord.white","nord.gray2"]
  hex-layer-unselected = ["nord.black","nord.gray4"]
  packet-list-cell-focus = ["nord.white","nord.purple"]
  packet-list-cell-selected = ["nord.black","nord.gray3"]
  packet-list-row-focus = ["nord.white","nord.cyan"]
  packet-list-row-selected = ["nord.black","nord.gray4"]
  packet-struct-focus = ["nord.black","nord.cyan"]
  packet-struct-selected = ["nord.black","nord.gray4"]
  progress-complete = ["nord.white","nord.purple"]
  progress-default = ["nord.white","nord.black"]
  progress-spinner = ["nord.yellow","nord.black"]
  spinner = ["nord.yellow","nord.white"]
  stream-client = ["nord.white","nord.red"]
  stream-match = ["nord.white","nord.yellow"]
  stream-search = ["nord.white","nord.black"]
  stream-server = ["nord.white","nord.blue"]
  title = ["nord.red","unused"]
