tap "datawire/blackbird"
tap "gromgit/fuse"
tap "hidetatz/tap"
tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/services"
tap "jesseduffield/lazygit"
tap "k8sgpt-ai/k8sgpt"
tap "kubecolor/tap"
tap "making/tap"
tap "mongodb/brew"
tap "ngrok/ngrok"
tap "redis-stack/redis-stack"
tap "shaunsingh/sfmono-nerd-font-ligaturized"
tap "stripe/stripe-cli"
tap "yschimke/tap"
# Interpreted, interactive, object-oriented programming language
brew "python@3.10"
# Microsoft Azure CLI 2.0
brew "azure-cli"
# Core application library for C
brew "glib"
# Validating, recursive, caching DNS resolver
brew "unbound"
# GNU Transport Layer Security (TLS) Library
brew "gnutls"
# Emacs dependency management
brew "cask"
# Get a file from an HTTP, HTTPS or FTP server
brew "curl"
# Libraries to talk to Microsoft SQL Server and Sybase databases
brew "freetds"
# General-purpose scripting language
brew "php", restart_service: true
# Dependency Manager for PHP
brew "composer"
# Programming language for highly scalable real-time systems
brew "erlang"
# User-friendly command-line shell for UNIX-like operating systems
brew "fish"
# OpenType text shaping engine
brew "harfbuzz"
# Development kit for the Java programming language
brew "openjdk"
# Reformats Java source code to comply with Google Java Style
brew "google-java-format"
# Open-source build automation tool based on the Groovy and Kotlin DSL
brew "gradle"
# GNU grep, egrep and fgrep
brew "grep"
# GNU Ubiquitous Intelligent Language for Extensions
brew "guile"
# Kubernetes package manager
brew "helm"
# Improved top (interactive process viewer)
brew "htop"
# User-friendly cURL replacement (command-line HTTP client)
brew "httpie"
# Kubernetes CLI To Manage Your Clusters In Style!
brew "k9s"
# Kubernetes command-line interface
brew "kubernetes-cli", link: false
# Provides library functionality for FIDO U2F & FIDO 2.0, including USB
brew "libfido2"
# Bare libuv bindings for lua
brew "luv"
# Java-based project management
brew "maven"
# Platform built on V8 to build network applications
brew "node"
# MongoDB Shell to connect, configure, query, and work with your MongoDB database
brew "mongosh"
# Open source relational database management system
brew "mysql", restart_service: true
# Fast, highly customisable system info script
brew "neofetch"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# HTTP/2 C Library
brew "nghttp2"
# Platform built on V8 to build network applications
brew "node@14"
# Platform built on V8 to build network applications
brew "node@16"
# Fast, disk space efficient package manager
brew "pnpm"
# Object-relational database system
brew "postgresql@14", restart_service: true
# Interpreted, interactive, object-oriented programming language
brew "python@3.8"
# Interpreted, interactive, object-oriented programming language
brew "python@3.9"
# Persistent key-value database, with built-in net interface
brew "redis"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Prints a steam locomotive if you type sl instead of ls
brew "sl"
# Organize software neatly under a single directory tree (e.g. /usr/local)
brew "stow"
# Nodejs-based tool for optimizing SVG vector graphics files
brew "svgo"
# User interface to the TELNET protocol
brew "telnet"
# Graphical network analyzer and capture tool
brew "wireshark", link: false
# Terminal UI for tshark, inspired by Wireshark
brew "termshark"
# Tool to build, change, and version infrastructure
brew "terraform"
# Terminal multiplexer
brew "tmux"
# Executes a program periodically, showing output fullscreen
brew "watch"
# Tools for the WireGuard secure network tunnel
brew "wireguard-tools"
# UNIX shell (command interpreter)
brew "zsh"
# Additional completion definitions for zsh
brew "zsh-completions"
# Local dev environment attached to a remote Kubernetes cluster
brew "datawire/blackbird/telepresence"
# File system client based on SSH File Transfer Protocol
brew "gromgit/fuse/sshfs-mac"
# A simple terminal UI for git commands, written in Go
brew "jesseduffield/lazygit/lazygit"
brew "k8sgpt-ai/k8sgpt/k8sgpt"
# Colorize your kubectl output
brew "kubecolor/tap/kubecolor"
# RSocket Client CLI (RSC)
brew "making/tap/rsc"
# High-performance, schema-free, document-oriented database
brew "mongodb/brew/mongodb-community"
# An interactive JavaScript command-line interface to MongoDB
brew "mongodb/brew/mongodb-community-shell"
# Stripe CLI utility
brew "stripe/stripe-cli/stripe"
# Command-line interface for 1Password
cask "1password-cli"
# Sound and music editor
cask "ableton-live-suite"
# Collection of apps and services for photography, design, video, web, and UX
cask "adobe-creative-cloud"
# JDK from the Java User Group (JUG)
cask "adoptopenjdk"
cask "blackhole"
# 3D creation suite
cask "blender"
# Voice and text chat software
cask "discord"
# App to build and share containerized applications and microservices
cask "docker"
# Online diagram software
cask "drawio"
# Free monospaced font with programming ligatures
cask "font-fira-code"
# Developer targeted fonts with a high number of glyphs
cask "font-hack-nerd-font"
# Developer targeted fonts with a high number of glyphs
cask "font-jetbrains-mono-nerd-font"
# Set of tools to manage resources and applications hosted on Google Cloud
cask "google-cloud-sdk"
# Java IDE by JetBrains
cask "intellij-idea"
# Terminal emulator as alternative to Apple's Terminal app
cask "iterm2"
# Personal data manager focusing on security
cask "keepassx"
# GPU-based terminal emulator
cask "kitty"
# File system integration
cask "macfuse"
# Provides updates to various Microsoft products
cask "microsoft-auto-update"
# Meet, chat, call, and collaborate in just one place
cask "microsoft-teams"
# Reverse proxy, secure introspectable tunnels to localhost
cask "ngrok"
# File system integration
cask "osxfuse"
# Collaboration platform for API development
cask "postman"
# Redis server with additional database capabilities and the visualisation tool RedisInsight.
cask "redis-stack"
# A graphical tool for visualizing data and managing Redis databases
cask "redis-stack-redisinsight"
# Redis Stack Server install a Redis server with additional database capabilities
cask "redis-stack-server"
# Team communication and collaboration software
cask "slack"
# Music streaming service
cask "spotify"
# Multi-platform VNC client and server
cask "tigervnc-viewer"
# Open-source code editor
cask "visual-studio-code"
# Native desktop client for WhatsApp
cask "whatsapp"
# Network protocol analyzer
cask "wireshark"
# Open-source version of the X.Org X Window System
cask "xquartz"
